USE [master]
GO

/****** Object:  Database [CODING_CHALLENGE]    Script Date: 7/13/2019 8:21:11 AM ******/
CREATE DATABASE [CODING_CHALLENGE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CODING_CHALLENGE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CODING_CHALLENGE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CODING_CHALLENGE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CODING_CHALLENGE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CODING_CHALLENGE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CODING_CHALLENGE] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET ARITHABORT OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CODING_CHALLENGE] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CODING_CHALLENGE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CODING_CHALLENGE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CODING_CHALLENGE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CODING_CHALLENGE] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CODING_CHALLENGE] SET  MULTI_USER 
GO

ALTER DATABASE [CODING_CHALLENGE] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CODING_CHALLENGE] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CODING_CHALLENGE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CODING_CHALLENGE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CODING_CHALLENGE] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CODING_CHALLENGE] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CODING_CHALLENGE] SET  READ_WRITE 
GO

